### PR TITLE
Migrate from Eclipse EMF to JAXB

### PR DESCRIPTION
**Pull request by mkrebs81**
- JAXB is used to create generated classes from XML schema
- Eclipse and EMF libraries no longer needed

### CODE REVIEW

**Comment by mkrebs81** [comment]
checks seem to fail temporarily because of missing snapshot packages in nexus

**Comment by mkrebs81** [comment]
integration tests are working again; ready to merge

**Comment by ergo-furrer** [comment]
> integration tests are working again; ready to merge

I think I should publish a sgr-specification SNAPSHOT without a JAXB prefix to NEXUS now. Then we change the gradle files back again.
OK for you?

**Comment by ergo-furrer** [comment]
> > integration tests are working again; ready to merge
> 
> I think I should publish a sgr-specification SNAPSHOT without a JAXB prefix to NEXUS now. Then we change the gradle files back again. OK for you?

OK published.

**Comment by mkrebs81** [comment]
> > > integration tests are working again; ready to merge
> > 
> > 
> > I think I should publish a sgr-specification SNAPSHOT without a JAXB prefix to NEXUS now. Then we change the gradle files back again. OK for you?
> 
> OK published.

OK I will commit an update in a few minutes

**Comment by mkrebs81** [comment]
I continued working in a different branch which includes this, so this PR is outdated (sorry)

**Pull request closed without merging**
