### PR TITLE
merge refactoring and ServiceLoader implementation

### PR DESCRIPTION
**Pull request by mkrebs81**
tested with testlab integration framework:

- Modbus RTU with multiple devices on bus
- REST API

### CODE REVIEW

**Comment by mkrebs81** [comment]
@ergo-furrer the implementation is ready since I merged you latest bugfix. the check has failed because the new driver api has not yet been released. it works on local host.

**Review by ergo-furrer — DISMISSED** [review]

**Comment by ergo-furrer** [comment]
@mkrebs81 Looks good to me. Nice solution for the MQTT filter.

**Comment by mkrebs81** [comment]
@ergo-furrer I have prepared the other repository (SGrJavaDrivers) as well.
Do you have any further input regarding the driver API? If not, I could start by creating that release first, and then the other components will at least compile.

Perhaps I need to rethink the handling of snapshots in the future, because it's a problem during the development of a new version with changed interfaces.

**Comment by ergo-furrer** [comment]
> @ergo-furrer I have prepared the other repository (SGrJavaDrivers) as well. Do you have any further input regarding the driver API? If not, I could start by creating that release first, and then the other components will at least compile.
> 

From my point of view, you could start creating the release.  I did build the Modbus/HttpClient/MQTT drivers locally did the Commhandler unit-tests. I also tested using my Wago und Clemap and it worked.

> Perhaps I need to rethink the handling of snapshots in the future, because it's a problem during the development of a new version with changed interfaces.

I used publishToMavenLocal and this was fine for me. But I see the Problem with the Pipelines. Maybe we can solve the Problem when we allow custom names such as -SERVICE_LOADER instead of -SNAPSHOT in cases when required. The custom name could also be configured within the gradle.properties. Did not think that trough but it could be a solution.

**Comment by mkrebs81** [comment]
> I used publishToMavenLocal and this was fine for me. But I see the Problem with the Pipelines. Maybe we can solve the Problem when we allow custom names such as -SERVICE_LOADER instead of -SNAPSHOT in cases when required. The custom name could also be configured within the gradle.properties. Did not think that trough but it could be a solution.

I'll think about it. Maybe my approach with the build parameters was not so good.

@ergo-furrer please approve so I can merge the code

**Pull request merged**
